# Build stage
FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copy toàn bộ mã nguồn
COPY . .

# Copy file .env.production vào làm .env để build
COPY .env.local .env

# Build production
RUN npm run build

# Production stage
FROM node:18-alpine AS runner

WORKDIR /app

# Copy app từ build stage
COPY --from=builder /app ./

# Cài minimal deps cho chạy production
RUN npm install --omit=dev

EXPOSE 3000

# Chạy Next.js production mode
CMD ["npm", "start"]
