# Build stage
FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Production stage
FROM node:18-alpine AS runner

WORKDIR /app

COPY --from=builder /app ./

# Optional: nếu bạn dùng .env.production trong Next.js
# COPY .env.production .env

EXPOSE 3000

CMD ["npm", "start"]
