FROM node:18 AS build

WORKDIR /app
COPY package*.json ./
RUN npm install 
COPY . .
COPY .env .env
ENV NODE_OPTIONS=--max-old-space-size=1536
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80