name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push backend
        run: |
          docker build -t tranvukien125/doan_tot_nghiep_backend:latest ./shofy-fashion-ecommerce-backend
          docker push tranvukien125/doan_tot_nghiep_backend:latest

      - name: Build and push frontend (client)
        run: |
          docker build -t tranvukien125/doan_tot_nghiep_client:latest ./client
          docker push tranvukien125/doan_tot_nghiep_client:latest

      - name: Build and push frontend_admin
        run: |
          docker build -t tranvukien125/doan_tot_nghiep_admin:latest ./Admin/admin-web
          docker push tranvukien125/doan_tot_nghiep_admin:latest

      - name: SSH into VPS and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/WDP
            docker-compose down
            docker-compose pull
            docker-compose up -d
            docker image prune -af
